list1=input("enter digits of list1:")
list2=input("enter digits of list2:")
list3=input("enter values of list3:")
A=list1.split()
B=list2.split()
C=list3.split()
print(A)
print(B)
print(C)
print(f"{A}\n{B}\n{C}")
